Berlin Open Data portal
technologiestiftung/berlin-open-source-portal pull request #152
Opened 2021-04-26 16:49 UTC by knudmoeller

text, metadata and images for daten.berlin.de aka "Berlin Open Data"

2021-04-27 15:22 UTC, dnsos commented
Hey @knudmoeller, thank you for the contribution. We are happy to include the data portal projects in our list.

The `repository` field in the front matter actually doesn't expect a non-repository link (and this might cause issues with our script for fetching data from the GitHub API). However, we see that it makes sense to present the repositories as a bundle. I will come back to you here with a solution very soon.

2021-04-28 10:02 UTC, knudmoeller commented
Cool, thanks! Let me know if you need any further input from me. If the non-repository link doesn't work out, I could create a dummy meta-repository "Berlin Open Data" with just a README and links to the individual 'real' repos. I'm not sure what would be better.

2021-04-29 09:39 UTC, dnsos requested changes
So, we have decided to provide the option for repository collections generally and now added a front matter field for this in #153 

If you could simply update the name of your field as noted in my comment, we're good to go and merge this. Thank you! Glad the repos are coming to the site.

2021-04-29 09:39 UTC, dnsos commented on src/projects/berlin-open-data.md
> +repository: https://github.com/search?q=org%3Aberlinonline+topic%3Aberlinopendata
We now have a field specifically for this case: `repository_collection`. Simply rename the key here.

2021-04-29 12:38 UTC, knudmoeller commented
Ok, I've made the change in the PR branch. That's all you need, right?

2021-04-29 16:14 UTC, dnsos approved these changes

2021-04-29 16:15 UTC, dnsos commented
Perfect, thank you. Yes, that's all that's needed. Merging this now!

2021-04-29 16:15 UTC, merged